Extract `deflicker` plugin and split `Screen` state
TheBevyFlock/bevy-template pull request #57
Opened 2024-07-07 23:34 UTC by MiniaczQ

2024-07-07 23:52 UTC, janhohenheim approved these changes

2024-07-07 23:54 UTC, benfrankel approved these changes
Feel free to ignore the system rename suggestions.

2024-07-07 23:54 UTC, benfrankel commented on src/core/deflicker.rs
> +fn make_window_invisible(mut window: Query<&mut Window>) {
```suggestion
fn hide_window(mut window: Query<&mut Window>) {
```

2024-07-07 23:54 UTC, benfrankel commented on src/core/deflicker.rs
> +fn make_window_visible(mut window: Query<&mut Window>) {
```suggestion
fn show_window(mut window: Query<&mut Window>) {
```

2024-07-08 00:05 UTC, janhohenheim requested changes

2024-07-08 00:05 UTC, janhohenheim commented on src/core/mod.rs
> +pub mod window;
```suggestion
pub(crate) mod window;
```

2024-07-08 00:05 UTC, janhohenheim commented on src/core/window.rs
> +pub enum WindowState {
Does this also need to go into the `dev` debug prints?

2024-07-08 00:06 UTC, janhohenheim commented on src/core/window.rs
> +pub enum WindowState {
(This applies to `BootingState`)

2024-07-08 00:07 UTC, benfrankel approved these changes

2024-07-08 00:08 UTC, janhohenheim approved these changes

2024-07-08 00:09 UTC, benfrankel approved these changes
Will be very easy to move `booting.rs` back into `window.rs` later if it turns out to be possible while decoupling the asset loading stuff. So LGTM.

2024-07-08 00:17 UTC, merged